# Generated by Django 5.0.4 on 2025-02-05 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0005_rename_title_image_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prep_time', models.DurationField(blank=True, null=True)),
                ('cook_time', models.DurationField(blank=True, null=True)),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('private', 'Private'), ('unlisted', 'Unlisted'), ('friends', 'Friends'), ('public', 'Public')], default='draft', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipies', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipies', to='media.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
