# Generated by Django 5.0.4 on 2025-02-06 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('system', models.PositiveSmallIntegerField(choices=[(0, 'Imperial'), (1, 'Metric')])),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'Volume'), (1, 'Weight')])),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=1.0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipe.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
