# Generated by Django 5.0.4 on 2025-02-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_unit_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='visibility',
        ),
    ]
