# Generated by Django 5.0.4 on 2025-02-06 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_visibility'),
        ('recipe', '0003_remove_recipe_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='common.visibility'),
            preserve_default=False,
        ),
    ]
