# Generated by Django 5.0.4 on 2025-02-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='handle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
