# Generated by Django 5.0.4 on 2025-02-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
    ]
