# Generated by Django 5.0.4 on 2025-02-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_cook_time_recipe_prep_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('recipe', 'sequence')},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
