# Generated by Django 5.0.4 on 2025-02-12 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_collection'),
        ('recipe', '0008_alter_ingredient_options_ingredient_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_collections', to='common.collection')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_collections', to='recipe.recipe')),
            ],
            options={
                'ordering': ('recipe', 'sequence'),
            },
        ),
    ]
