# Generated by Django 5.0.4 on 2025-02-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='name',
        ),
    ]
