services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./server/.env.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    depends_on:
      - db
      
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./server/.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - server

volumes:
  postgres_data:
  static_volume:
  media_volume: