services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - ./server/.env.dev
    depends_on:
      - db

  client:
    image: client
    volumes:
      - /client/node_modules
      - ./client:/usr/src/app
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      NPM_CONFIG_UNSAFE_PERM: true
    ports:
      - 3000:3000
      # - 9228:9228
    # command: node --experimental-loader=@vavite/node-loader
    depends_on:
      - server

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lemio
      - POSTGRES_PASSWORD=lemio
      - POSTGRES_DB=lemio_dev

volumes:
  postgres_data: