services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.dev
    depends_on:
      - db

  # client:
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   command: npm run dev
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - django

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lemio
      - POSTGRES_PASSWORD=lemio
      - POSTGRES_DB=lemio_dev

volumes:
  postgres_data: