# Generated by Django 5.0.4 on 2025-02-06 02:15

from django.db import migrations, models

from server.fields import ColorField


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=15)),
                ('color', ColorField(default='#777', max_length=25)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
