# Generated by Django 5.0.4 on 2025-02-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visibility',
            options={'ordering': ('sequence',)},
        ),
    ]
