# Generated by Django 5.0.4 on 2025-02-08 00:39

import django.core.validators
import server.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_visibility_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibility',
            name='color',
            field=server.fields.ColorField(blank=True, default='#777', help_text='Valid Hexadecimal Color Code, ie. #0066ff. Use #000 for null', max_length=7, null=True, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
