# Generated by Django 5.0.4 on 2025-02-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_visibility_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
