# Generated by Django 5.0.4 on 2025-02-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
